version: "3.3"

secrets:
  db_passwd:
    file: db_passwd.txt

services:
  bot:
    image: "ssttkkl/bot-kuraku:latest"
    container_name: "bot"
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8080"
    env_file:
      - .env

  bot-postgres:
    image: "postgres:latest"
    container_name: "bot-postgres"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_passwd
    volumes:
      - "bot-postgres-data:/var/lib/postgresql/data"
    secrets:
      - db_passwd

volumes:
  bot-postgres-data:
