version: "3.3"

secrets:
  db_passwd:
    file: db_passwd.txt

services:
  bot:
    image: "ssttkkl/bot-kuraku:latest"
    container_name: "bot"
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8080"
    volumes:
      - ./.env.prod:/app/.env.prod

  bot-postgres:
    image: "postgres:15"
    container_name: "bot-postgres"
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_passwd
    volumes:
      - "bot-postgres-data:/var/lib/postgresql/data"
    secrets:
      - db_passwd

  bot-chronocat:
    image: "yuukinya/chronocat-docker:latest"
    tty: true
    container_name: "bot-chronocat"
    restart: always
    ports:
      - "5900:5900"
      - "16530:16530"
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - bot-config-data:/root/.chronocat/config
      - bot-chronocat-data:/root/.config/QQ

volumes:
  bot-postgres-data:
  bot-config-data:
  bot-chronocat-data:
