version: "3.3"

secrets:
  db_passwd:
    file: db_passwd.txt

services:
  bot:
    image: "ssttkkl/bot-kuraku-bot:latest"
    # build: bot
    container_name: "bot"
    restart: always
    environment:
      - "HOST=0.0.0.0"
      - "PORT=8080"
    volumes:
      - ./.env.prod:/app/.env.prod

  bot-postgres:
    image: "postgres:15"
    container_name: "bot-postgres"
    restart: always
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_passwd
    volumes:
      - "bot-postgres-data:/var/lib/postgresql/data"
    secrets:
      - db_passwd

  bot-napcat:
    image: "mlikiowa/napcat-docker:latest"
    container_name: "bot-napcat"
    restart: always
    ports:
      - "6099:6099"
    environment:
      - TZ=Asia/Shanghai
      - ACCOUNT=${QQ_ACCOUNT}
      - NAPCAT_GID=0
      - NAPCAT_UID=0
      - WSR_ENABLE=true
      - WS_URLS=["ws://bot:8080/onebot/v11/ws/"]
    volumes:
      - bot-napcat-config:/app/napcat/config
      - bot-napcat-data:/app/.config/QQ

volumes:
  bot-postgres-data:
  bot-napcat-config:
  bot-napcat-data:
